In [2]:
import numpy as np

NumPy Array

In [49]:
'''









How to build an array of all combinations of two NumPy arrays?
How to add a border around a NumPy array?
How to compare two NumPy arrays?
How to check whether specified values are present in NumPy array?
How to get all 2D diagonals of a 3D NumPy array?
Flatten a Matrix in Python using NumPy
Flatten a 2d numpy array into 1d array
Move axes of an array to new positions
Interchange two axes of an array
NumPy – Fibonacci Series using Binet Formula
Counts the number of non-zero values in the array
Count the number of elements along a given axis
Trim the leading and/or trailing zeros from a 1-D array
Change data type of given numpy array
Reverse a numpy array
How to make a NumPy array read-only?
'''
#Q1-How to create an empty and a full NumPy array?
empty_array = np.empty([5,2])
print("Q1\n",empty_array)
full_array = np.full([5,2], 10)
print("Q1\n",full_array)

#Q2-Create a Numpy array filled with all zeros
zeros_array = np.zeros((5,2))
print("Q2\n",zeros_array)

#Q3-Create a Numpy array filled with all ones
ones_array = np.ones((5,2))
print("Q3\n",ones_array)

#Q4-Check whether a Numpy array contains a specified row
array_q4 = np.array([1 , 2 ,3])
print("Q4\n",[1,2,3,4,5] in array.tolist())

#Q5-How to Remove rows in Numpy array that contains non-numeric values?
array_q5 = np.array([[1 , 2 ,3], 
                  [41, np.nan, np.nan]])
print("Q5")
print(array_q5)
array_q5 = array_q5[~np.isnan(array_q5).any(axis=1)]
print(array_q5) #np.isnan shows which elements are Not a Number

#Q6-Remove single-dimensional entries from the shape of an array
array_q6 = np.zeros((3, 1, 4)) # 3 arrays with 1 row and 4 collumns
print("Q6\n", array_q6)
print(np.squeeze(array_q6).shape)

#Q7-Find the number of occurrences of a sequence in a NumPy array

array_q7 = np.array([[1, 2, 9, 4],  
                   [3, 4, 9, 4], 
                   [5, 6, 9, 7], 
                   [7, 9, 4, 3]])
#TODO
#print("Q7\n", result)

#Q8-Find the most frequent value in a NumPy array
array_q8 = np.array([1,2,3,4,5,1,2,1,1,1]) 
print("Q8\n",np.bincount(array_q8).argmax()) #Count number of occurrences of each value in array of non-negative ints.

#Q9-Combining a one and a two-dimensional NumPy Array
array1_q9 = np.arange(5) 
array2_q9 = np.arange(10).reshape(2,5)

print("Q9")
for a, b in np.nditer([array1_q9, array2_q9]): 
    print(a,":",b)

Q1
 [[0.0e+000 4.9e-324]
 [9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323]
 [3.0e-323 3.5e-323]
 [4.0e-323 4.4e-323]]
Q1
 [[10 10]
 [10 10]
 [10 10]
 [10 10]
 [10 10]]
Q2
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Q3
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Q4
 False
Q5
[[ 1.  2.  3.]
 [41. nan nan]]
[[1. 2. 3.]]
Q6
 [[[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]]
(3, 4)
Q8
 1
Q9
0 : 0
1 : 1
2 : 2
3 : 3
4 : 4
0 : 5
1 : 6
2 : 7
3 : 8
4 : 9
